### ISSUE TITLE
Out of the blue: TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by mbac** [glibsonoran/Plush-for-ComfyUI#146]
Hi!

After a successful installation from scratch (new cloud machine), I noticed this error that I'd never seen before:

```
[ERROR] An error occurred while retrieving information for the 'Enhancer' node.
Traceback (most recent call last):
  File "/workspace/ComfyUI/server.py", line 563, in get_object_info
    out[x] = node_info(x)
  File "/workspace/ComfyUI/server.py", line 530, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/workspace/ComfyUI/custom_nodes/Plush-for-ComfyUI/style_prompt.py", line 531, in INPUT_TYPES
    cFig=cFigSingleton()
  File "/workspace/ComfyUI/custom_nodes/Plush-for-ComfyUI/style_prompt.py", line 58, in __new__
    cls._instance.get_file()
  File "/workspace/ComfyUI/custom_nodes/Plush-for-ComfyUI/style_prompt.py", line 139, in get_file
    self._groq_models = self._model_fetch.fetch_models(RequestMode.GROQ, self._groq_key)
  File "/workspace/ComfyUI/custom_nodes/Plush-for-ComfyUI/fetch_models.py", line 204, in fetch_models
    return self.strategy.fetch_models(self.api_obj, key)
  File "/workspace/ComfyUI/custom_nodes/Plush-for-ComfyUI/fetch_models.py", line 94, in fetch_models
    client = api_obj(api_key=key)
  File "/workspace/ComfyUI/vcomfy/lib/python3.10/site-packages/groq/_client.py", line 99, in __init__
    super().__init__(
  File "/workspace/ComfyUI/vcomfy/lib/python3.10/site-packages/groq/_base_client.py", line 855, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
  File "/workspace/ComfyUI/vcomfy/lib/python3.10/site-packages/groq/_base_client.py", line 753, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
```

This is in ComfyUI 0.3.5; of course I've been installing nodes (and Python libraries) in a different order than before, so maybe there's some form of incompatibility? You can find the pip freeze from Comfy's venv on this [pastebin](https://pastebin.com/9YBELL78).

Thanks!

**Comment by EnragedAntelope** [comment]
In your venv environment can you try 
pip install —upgrade groq

in case you have an older version that doesn’t support that function?
You’d need to restart comfy after updating.

**Comment by glibsonoran** [comment]
This is an issue with the groq library.  It appears to be receiving an unexpected parameter: *proxies*, most likely from its dependency the httpx library.  Your httpx library looks up to date 0.28.0, groq is out of date one version 0.12.0 vs 0.13.0 on PyPI.  The documentation on PYPI doesn't indicate that groq has a dependency on a specific version of httpx.

I can't imagine that a version that recent would be the issue unless they just happened to introduce a bug and fixed it in the next version.  You can try bringing your groq up to v.0.13.0 and see if that fixes it.

```pip install --upgrade groq
pip show groq```

If that doesn't fix it I suspect the issue might be an undocumented incompatibility between httpx and groq.  My installation works using httpx 0.25.1, so you could try:

`pip install httpx==0.25.1`

My groq version is 0.5.0 Y FYI.

**Comment by mbac** [comment]
Confirmed working with `httpx==0.25.1`; I can run more tests if you think it could be useful…

Thanks!

**Comment by glibsonoran** [comment]
Good news!  I'm going to leave this issue open for now in case someone else comes across this error.

**Comment by glibsonoran** [comment]
close
